# Generated by Django 5.0.2 on 2024-03-06 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productcategory_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', max_length=255)),
                ('content', models.TextField()),
                ('city', models.CharField(default='Default City', max_length=100)),
                ('area', models.IntegerField(default=0)),
                ('locality', models.CharField(default='Default Locality', max_length=100)),
                ('floor', models.IntegerField(default=1)),
                ('property_type', models.CharField(choices=[('house', 'Residential House'), ('apartment', 'Apartment'), ('society', 'Cooperative Society'), ('plot', 'Plot'), ('land', 'Land'), ('builder_floor', 'Builder Floor')], default='apartment', max_length=20)),
                ('transaction_type', models.CharField(choices=[('lease_hold', 'Lease Hold'), ('free_hold', 'Free Hold')], default='free_hold', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('area_sqft', models.IntegerField(default=0)),
                ('owner_name', models.CharField(default='Default Owner', max_length=255)),
                ('contact_number', models.CharField(default='Default Contact Number', max_length=15)),
                ('facing_direction', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('other', 'Other')], default='north', max_length=10)),
                ('status', models.CharField(choices=[('ready_to_move', 'Ready to Move'), ('under_construction', 'Under Construction')], default='ready_to_move', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='property_videos/')),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='store.property')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
