# Generated by Django 5.0.2 on 2024-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_property_propertyimage_propertyvideo_delete_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact_number',
            field=models.CharField(default='Default Contact Number', max_length=50),
        ),
    ]
