# Generated by Django 5.0.2 on 2024-03-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_propertyimage_created_at_propertyimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='option',
            field=models.CharField(choices=[('sell', 'SELL'), ('rent', 'RENT')], default='rent', max_length=10),
        ),
    ]
