version: '3'

services:
  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - redis
      - celery
    networks:
      - backend
      - frontend

  redis:
    image: redis:latest
    networks:
      - backend

  celery:
    build: .
    command: celery -A ecom worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    depends_on:
      - web
    networks:
      - frontend
      - backend

networks:
  backend:
  frontend:
