version: "3.10"

networks:
  # Define your custom network name here (e.g., my-production-network)
  my-production-network:

services:
  app:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis  # Assuming service discovery resolves to 'redis' in your network
      - DJANGO_SECRET_KEY=${SECRET_KEY}  # Replace with a strong secret key
      - CELERY_BROKER_URL=redis://redis:6379/0  # Adjust port if needed
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  # Adjust port if needed
    volumes:
      - ./media:/app/media  # Mount media directory for persistence
      - ./static:/app/static  # Mount static directory for persistence
    ports:
      - 8000:8000
    depends_on:
      - redis
    networks:
      - my-production-network  # Add the service to the custom network

  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly yes --port 6379

    networks:
      - my-production-network  # Add the service to the custom network
