# Generated by Django 5.0.2 on 2024-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_login_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_verification_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
